# Use an official PostgreSQL as the base image
FROM postgres:latest

# Set environment variables for the database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=pwd123456
ENV POSTGRES_DB=mydatabase

# Expose the PostgreSQL port
EXPOSE 5432
